# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: postgresql
  database: facebookapi
  pool: 5
  timeout: 5000
  port: 5555
  username: postgres
  password: password@123

